### PR TITLE
github link added

### LINKED ISSUE #67: add github link in hacksquad website
Just realised there is no github link of this repo in the website. 
I found an enhancement and thought of raising an issue but then found there is no github link in the website. so had to google it. 
Having a github link might be of some use to other folks too.

@nevo-david

### PR DESCRIPTION
**Pull request by saimaheshtaduri**
Screenshot (41)

resolves #67 
@nevo-david  please review it.

### CODE REVIEW

**Comment by saimaheshtaduri** [comment]
@nevo-david please review.

**Review by TheLearneer — APPROVED** [review]
LGTM

**Comment by saimaheshtaduri** [comment]
Thanks @TheLearneer :)

**Review by nevo-david — APPROVED** [review]
Thank you!

**Pull request merged**
