### PR TITLE
Added field for showing rank in the 'My Squad' page

### LINKED ISSUE #56: Show team ranking on my team page
Instead of having to go to leaderboard and view team ranking, it would be quite convenient to see team rankings on the my squad page itself maybe below or above Score of the team

### PR DESCRIPTION
**Pull request by PratyayDhond**
I couldn't figure it out how to open mySquad page on localhost, and there's no rank variable here in the database of the teams, but I would suggest to pass the (index  + 1) of the current team to the my squad component and pass that value as a parameter for rank variable

Closes #56 - partially completed

### CODE REVIEW

**Comment by PratyayDhond** [comment]
@nevo-david please check this out

**Comment by nevo-david** [comment]
But we don't have "rank" in the DB.

**Comment by PratyayDhond** [comment]
yuppp, @nevo-david, that's why I suggested to pass the index at which the team is as a prop and show that in place of rank, I am not able to configure the github signin that's why I suggested that

**Review by bsantosh909 — CHANGES_REQUESTED** [review]
Doesn't solve the issue, please let us know if you are still willing to work on it.

**Comment by vimode** [comment]
Is this still being worked on? Can I try to add this feature? 

@PratyayDhond  I think you are on the right track, of using the data (`teams`) from `api/leaderboard.js` and use the index to display the current rank. 

But that can be done with fetching it along with `/api/teams` in the `myteam.jsx`, pass the index as prop along with `info`

**Pull request closed without merging**
