### PR TITLE
feat: add react-toastify

### PR DESCRIPTION
**Pull request by rahmat-st**

### CODE REVIEW

**Comment by nevo-david** [comment]
I think it's better to put the Toast container inside the Layout

**Comment by rahmat-st** [comment]
image

may I put it under line 16?

**Comment by nevo-david** [comment]
Yes, try!

**Comment by nevo-david** [comment]
Can you also find and change the "alert('Message sent!');"
Just search it in the files

**Comment by rahmat-st** [comment]
image

I've updated it before in the first commit

**Comment by rahmat-st** [comment]
I only find two alert, copy to clipboard and message sent in team.jsx file

**Review by nevo-david — APPROVED** [review]

**Pull request merged**
